sonar.organization=feardelans
sonar.projectKey=feardelans_refactoring_proj
sonar.sources=src
sonar.tests=tests
sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
sonar.junit.reportPaths=reports/junit.xml
